/**
 * Mock Data per Percorsi Terapeutici
 * Questi dati simulano percorsi terapeutici per l'MVP
 */

import { TherapeuticPath } from '../models/therapeutic-path.model';

/**
 * Mock data per percorsi terapeutici
 * I patientId devono corrispondere a pazienti esistenti nel sistema
 */
export const MOCK_THERAPEUTIC_PATHS: TherapeuticPath[] = [
  // ========== PAZIENTE 1: Mario Rossi ==========
  {
    id: 'path-001',
    patientId: '1',
    name: 'Riabilitazione ginocchio DX post-artroscopia',
    description: 'Percorso riabilitativo post intervento di artroscopia meniscale',
    diagnosis: 'Lesione menisco mediale ginocchio destro',
    icdCode: 'S83.2',
    primaryOperatorId: '', // Verra popolato dinamicamente
    primaryOperatorName: 'Dr. Fisioterapista',
    status: 'active',
    startDate: '2024-11-15',
    expectedEndDate: '2025-02-15',
    plannedSessions: 20,
    completedSessions: 8,
    anamnesis: {
      id: 'anam-001',
      pathId: 'path-001',
      chiefComplaint: 'Dolore e rigidita al ginocchio destro post-intervento',
      historyOfPresentIllness:
        'Paziente operato il 10/11/2024 per lesione meniscale. Riferisce dolore 6/10 al carico, limitazione ROM in flessione.',
      onsetDate: '2024-11-10',
      painScale: 6,
      painLocation: 'Ginocchio destro, zona mediale',
      aggravatingFactors: ['Camminata prolungata', 'Scale', 'Accovacciamento'],
      relievingFactors: ['Riposo', 'Ghiaccio', 'FANS'],
      pastMedicalHistory: 'Ipertensione arteriosa in terapia',
      medications: ['Ramipril 5mg', 'Ketoprofene al bisogno'],
      allergies: ['Penicillina'],
      patientGoals: 'Tornare a giocare a calcetto',
      therapistGoals: 'Recupero ROM completo, rinforzo muscolare, ritorno alle attivita sportive',
      createdAt: '2024-11-15T09:00:00',
      updatedAt: '2024-11-15T09:00:00',
      createdBy: 'op-fisio-001',
    },
    treatments: [
      {
        id: 'treat-001',
        pathId: 'path-001',
        operatorId: 'op-fisio-001',
        operatorName: 'Dr. Fisioterapista',
        date: '2024-11-15',
        startTime: '09:00',
        endTime: '10:00',
        duration: 60,
        type: 'evaluation',
        title: 'Valutazione iniziale',
        clinicalNotes:
          'ROM flessione 90 gradi, estensione completa. Ipotrofia quadricipite evidente. Test meniscali negativi post-operatorio.',
        treatmentDescription:
          'Valutazione funzionale completa, test articolari, misurazioni antropometriche, definizione obiettivi terapeutici.',
        patientResponse: 'Paziente collaborante e motivato',
        painScaleBefore: 6,
        painScaleAfter: 5,
        nextSteps: 'Iniziare mobilizzazione passiva e attiva assistita',
        createdAt: '2024-11-15T10:00:00',
      },
      {
        id: 'treat-002',
        pathId: 'path-001',
        operatorId: 'op-fisio-001',
        operatorName: 'Dr. Fisioterapista',
        date: '2024-11-18',
        startTime: '09:00',
        endTime: '10:00',
        duration: 60,
        type: 'standard',
        title: 'Seduta 1 - Mobilizzazione',
        clinicalNotes: 'Miglioramento ROM a 95 gradi. Edema in riduzione.',
        treatmentDescription:
          'Mobilizzazione passiva rotulea, stretching catena posteriore, esercizi isometrici quadricipite, crioterapia finale.',
        instrumentsUsed: [
          {
            instrumentId: 'instr-tecar-01',
            instrumentName: 'TECAR',
            categoryName: 'Elettroterapia',
            duration: 15,
            settings: 'Modalita capacitiva, 50%',
          },
        ],
        painScaleBefore: 5,
        painScaleAfter: 3,
        homeExercises: 'Isometrici quadricipite 3x10, stretching polpaccio 3x30sec',
        createdAt: '2024-11-18T10:00:00',
      },
      {
        id: 'treat-003',
        pathId: 'path-001',
        operatorId: 'op-fisio-001',
        operatorName: 'Dr. Fisioterapista',
        date: '2024-11-21',
        startTime: '09:00',
        endTime: '10:00',
        duration: 60,
        type: 'standard',
        title: 'Seduta 2 - Rinforzo',
        clinicalNotes: 'ROM 100 gradi. Inizio carico progressivo.',
        treatmentDescription:
          'Esercizi di rinforzo in catena cinetica chiusa, propriocezione su tavoletta, cyclette senza resistenza.',
        instrumentsUsed: [
          {
            instrumentId: 'instr-tecar-01',
            instrumentName: 'TECAR',
            categoryName: 'Elettroterapia',
            duration: 15,
          },
          {
            instrumentId: 'instr-laser-01',
            instrumentName: 'Laser',
            categoryName: 'Laserterapia',
            duration: 10,
            settings: '8J/cm2',
          },
        ],
        painScaleBefore: 4,
        painScaleAfter: 2,
        homeExercises: 'Mini squat 3x10, ponte glutei 3x10, stretching quadricipite',
        createdAt: '2024-11-21T10:00:00',
      },
      {
        id: 'treat-004',
        pathId: 'path-001',
        operatorId: 'op-fisio-001',
        operatorName: 'Dr. Fisioterapista',
        date: '2024-11-25',
        startTime: '09:00',
        endTime: '10:00',
        duration: 60,
        type: 'standard',
        title: 'Seduta 3 - Propriocezione',
        clinicalNotes: 'ROM 110 gradi. Buon controllo muscolare.',
        treatmentDescription:
          'Esercizi propriocettivi avanzati, affondi assistiti, lavoro su bosu, tapis roulant 10 min.',
        painScaleBefore: 3,
        painScaleAfter: 2,
        homeExercises: 'Squat parete 3x15, equilibrio monopodalico 3x30sec per lato',
        createdAt: '2024-11-25T10:00:00',
      },
      {
        id: 'treat-005',
        pathId: 'path-001',
        operatorId: 'op-fisio-001',
        operatorName: 'Dr. Fisioterapista',
        date: '2024-11-28',
        startTime: '09:00',
        endTime: '10:00',
        duration: 60,
        type: 'standard',
        title: 'Seduta 4',
        clinicalNotes: 'ROM 115 gradi. Paziente riferisce miglioramento nelle ADL.',
        treatmentDescription: 'Rinforzo muscolare progressivo, esercizi pliometrici leggeri.',
        painScaleBefore: 2,
        painScaleAfter: 1,
        createdAt: '2024-11-28T10:00:00',
      },
      {
        id: 'treat-006',
        pathId: 'path-001',
        operatorId: 'op-fisio-001',
        operatorName: 'Dr. Fisioterapista',
        date: '2024-12-02',
        startTime: '09:00',
        endTime: '10:00',
        duration: 60,
        type: 'standard',
        title: 'Seduta 5',
        clinicalNotes: 'ROM completo. Inizio corsa leggera.',
        treatmentDescription: 'Corsa leggera 5 min, cambi direzione lenti, salti sul posto.',
        painScaleBefore: 2,
        painScaleAfter: 1,
        createdAt: '2024-12-02T10:00:00',
      },
      {
        id: 'treat-007',
        pathId: 'path-001',
        operatorId: 'op-fisio-001',
        operatorName: 'Dr. Fisioterapista',
        date: '2024-12-05',
        startTime: '09:00',
        endTime: '10:00',
        duration: 60,
        type: 'followup',
        title: 'Controllo intermedio',
        clinicalNotes:
          'Ottimo progresso. ROM completo, forza 4+/5, propriocezione buona. Paziente soddisfatto.',
        treatmentDescription:
          'Rivalutazione completa, test funzionali, aggiornamento piano terapeutico.',
        painScaleBefore: 1,
        painScaleAfter: 1,
        nextSteps: 'Proseguire con fase di ritorno allo sport',
        createdAt: '2024-12-05T10:00:00',
      },
      {
        id: 'treat-008',
        pathId: 'path-001',
        operatorId: 'op-fisio-001',
        operatorName: 'Dr. Fisioterapista',
        date: '2024-12-09',
        startTime: '09:00',
        endTime: '10:00',
        duration: 60,
        type: 'standard',
        title: 'Seduta 6 - Sport specifico',
        clinicalNotes: 'Inizio preparazione sport-specifica per calcetto.',
        treatmentDescription: 'Esercizi sport-specifici, cambi direzione, accelerazioni.',
        painScaleBefore: 1,
        painScaleAfter: 0,
        homeExercises: 'Programma di corsa progressiva, esercizi pliometrici',
        createdAt: '2024-12-09T10:00:00',
      },
    ],
    documents: [
      {
        id: 'doc-001',
        pathId: 'path-001',
        name: 'Referto RM ginocchio DX',
        type: 'pdf',
        url: '/assets/mock-docs/referto-rm.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 2456789,
        uploadedAt: '2024-11-14T15:30:00',
        category: 'referti',
      },
      {
        id: 'doc-002',
        pathId: 'path-001',
        name: 'Lettera dimissione ospedaliera',
        type: 'pdf',
        url: '/assets/mock-docs/dimissione.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 156789,
        uploadedAt: '2024-11-12T10:00:00',
        category: 'referti',
      },
      {
        id: 'doc-003',
        pathId: 'path-001',
        name: 'Foto pre-operatoria',
        type: 'image',
        url: '/assets/mock-docs/foto-pre.jpg',
        thumbnailUrl: '/assets/mock-docs/foto-pre-thumb.jpg',
        mimeType: 'image/jpeg',
        sizeBytes: 1234567,
        uploadedAt: '2024-11-08T14:00:00',
        category: 'immagini',
      },
    ],
    createdAt: '2024-11-15T08:00:00',
    updatedAt: '2024-12-09T10:00:00',
  },

  // Percorso completato per lo stesso paziente
  {
    id: 'path-002',
    patientId: '1',
    name: 'Cervicalgia cronica',
    description: 'Trattamento conservativo per cervicalgia muscolo-tensiva',
    diagnosis: 'Cervicalgia muscolo-tensiva cronica',
    icdCode: 'M54.2',
    primaryOperatorId: '',
    primaryOperatorName: 'Dr.ssa Fisioterapista',
    status: 'completed',
    startDate: '2024-06-01',
    actualEndDate: '2024-08-30',
    plannedSessions: 10,
    completedSessions: 10,
    anamnesis: {
      id: 'anam-002',
      pathId: 'path-002',
      chiefComplaint: 'Dolore cervicale persistente con cefalea tensiva',
      historyOfPresentIllness:
        'Paziente impiegato, lavoro sedentario al PC. Dolore cervicale da circa 6 mesi, peggiorato nelle ultime settimane.',
      painScale: 7,
      painLocation: 'Regione cervicale posteriore, trapezio bilaterale',
      aggravatingFactors: ['Lavoro prolungato al PC', 'Stress', 'Posture scorrette'],
      relievingFactors: ['Calore', 'Stretching', 'Riposo'],
      patientGoals: 'Ridurre il dolore e la frequenza delle cefalee',
      therapistGoals: 'Migliorare la postura, ridurre le contratture, educazione ergonomica',
      createdAt: '2024-06-01T10:00:00',
      updatedAt: '2024-06-01T10:00:00',
      createdBy: 'op-fisio-002',
    },
    treatments: [
      {
        id: 'treat-101',
        pathId: 'path-002',
        operatorId: 'op-fisio-002',
        operatorName: 'Dr.ssa Fisioterapista',
        date: '2024-06-01',
        startTime: '11:00',
        endTime: '12:00',
        duration: 60,
        type: 'evaluation',
        title: 'Valutazione iniziale',
        clinicalNotes:
          'Contrattura trapezio bilaterale marcata. ROM cervicale ridotto in rotazione. Trigger points attivi.',
        treatmentDescription: 'Valutazione posturale, test ROM, palpazione, definizione piano.',
        painScaleBefore: 7,
        painScaleAfter: 6,
        createdAt: '2024-06-01T12:00:00',
      },
      {
        id: 'treat-102',
        pathId: 'path-002',
        operatorId: 'op-fisio-002',
        operatorName: 'Dr.ssa Fisioterapista',
        date: '2024-08-30',
        startTime: '11:00',
        endTime: '12:00',
        duration: 60,
        type: 'discharge',
        title: 'Dimissione',
        clinicalNotes:
          'Paziente asintomatico. ROM completo. Riferisce netto miglioramento qualita vita.',
        treatmentDescription:
          'Seduta finale, consigli per mantenimento, programma esercizi domiciliari.',
        painScaleBefore: 1,
        painScaleAfter: 0,
        homeExercises:
          'Stretching cervicale quotidiano, pause dal lavoro ogni 45 min, esercizi posturali',
        createdAt: '2024-08-30T12:00:00',
      },
    ],
    documents: [],
    notes: 'Paziente molto collaborante. Ottimi risultati.',
    createdAt: '2024-06-01T09:00:00',
    updatedAt: '2024-08-30T12:00:00',
  },

  // ========== PAZIENTE 2: Anna Bianchi ==========
  {
    id: 'path-003',
    patientId: '2',
    name: 'Lombalgia acuta',
    description: 'Trattamento per episodio acuto di lombalgia',
    diagnosis: 'Lombalgia acuta aspecifica',
    icdCode: 'M54.5',
    primaryOperatorId: '',
    primaryOperatorName: 'Dr. Fisioterapista',
    status: 'active',
    startDate: '2024-12-10',
    expectedEndDate: '2025-01-10',
    plannedSessions: 8,
    completedSessions: 2,
    anamnesis: {
      id: 'anam-003',
      pathId: 'path-003',
      chiefComplaint: 'Dolore lombare acuto insorto dopo sforzo',
      historyOfPresentIllness:
        'Paziente riferisce insorgenza acuta di dolore lombare 5 giorni fa dopo aver sollevato un peso. Dolore irradiato al gluteo DX.',
      onsetDate: '2024-12-05',
      painScale: 8,
      painLocation: 'Regione lombare bassa, irradiazione gluteo DX',
      aggravatingFactors: ['Flessione del tronco', 'Stazione eretta prolungata', 'Tosse'],
      relievingFactors: ['Decubito laterale', 'FANS'],
      pastMedicalHistory: 'Nessuna patologia rilevante',
      patientGoals: 'Tornare al lavoro il prima possibile',
      therapistGoals: 'Riduzione dolore, recupero funzionale, prevenzione recidive',
      createdAt: '2024-12-10T14:00:00',
      updatedAt: '2024-12-10T14:00:00',
      createdBy: 'op-fisio-001',
    },
    treatments: [
      {
        id: 'treat-201',
        pathId: 'path-003',
        operatorId: 'op-fisio-001',
        operatorName: 'Dr. Fisioterapista',
        date: '2024-12-10',
        startTime: '14:00',
        endTime: '15:00',
        duration: 60,
        type: 'evaluation',
        title: 'Valutazione iniziale',
        clinicalNotes:
          'Contrattura paravertebrale marcata. SLR negativo. No deficit neurologici.',
        treatmentDescription:
          'Valutazione completa, esclusione red flags, terapia manuale decontratturante.',
        instrumentsUsed: [
          {
            instrumentId: 'instr-tecar-01',
            instrumentName: 'TECAR',
            categoryName: 'Elettroterapia',
            duration: 20,
            settings: 'Modalita resistiva, 40%',
          },
        ],
        painScaleBefore: 8,
        painScaleAfter: 6,
        homeExercises: 'Posizioni antalgiche, ghiaccio 15 min x 3/die',
        createdAt: '2024-12-10T15:00:00',
      },
      {
        id: 'treat-202',
        pathId: 'path-003',
        operatorId: 'op-fisio-001',
        operatorName: 'Dr. Fisioterapista',
        date: '2024-12-12',
        startTime: '14:00',
        endTime: '15:00',
        duration: 60,
        type: 'standard',
        title: 'Seduta 1',
        clinicalNotes: 'Lieve miglioramento. Paziente riesce a camminare meglio.',
        treatmentDescription:
          'Terapia manuale, mobilizzazione vertebrale, TECAR, esercizi di stabilizzazione.',
        instrumentsUsed: [
          {
            instrumentId: 'instr-tecar-01',
            instrumentName: 'TECAR',
            categoryName: 'Elettroterapia',
            duration: 20,
          },
        ],
        painScaleBefore: 6,
        painScaleAfter: 4,
        homeExercises: 'Cat-camel 2x10, bird-dog 2x8 per lato',
        createdAt: '2024-12-12T15:00:00',
      },
    ],
    documents: [],
    createdAt: '2024-12-10T13:30:00',
    updatedAt: '2024-12-12T15:00:00',
  },

  // ========== PAZIENTE 3: Paolo Verdi ==========
  {
    id: 'path-004',
    patientId: '3',
    name: 'Percorso dimagrimento',
    description: 'Programma nutrizionale e attivita fisica per perdita peso',
    diagnosis: 'Sovrappeso (BMI 28)',
    primaryOperatorId: '',
    primaryOperatorName: 'Dr. Nutrizionista',
    status: 'active',
    startDate: '2024-10-01',
    expectedEndDate: '2025-04-01',
    plannedSessions: 12,
    completedSessions: 5,
    anamnesis: {
      id: 'anam-004',
      pathId: 'path-004',
      chiefComplaint: 'Desiderio di perdere peso e migliorare lo stile di vita',
      historyOfPresentIllness:
        'Paziente con BMI 28, sedentario, alimentazione disordinata. Motivato a cambiare.',
      pastMedicalHistory: 'Ipercolesterolemia',
      medications: ['Nessuno'],
      allergies: [],
      patientGoals: 'Perdere 10 kg in 6 mesi',
      therapistGoals: 'Perdita peso graduale, educazione alimentare, aumento attivita fisica',
      createdAt: '2024-10-01T10:00:00',
      updatedAt: '2024-10-01T10:00:00',
      createdBy: 'op-nutri-001',
    },
    treatments: [
      {
        id: 'treat-301',
        pathId: 'path-004',
        operatorId: 'op-nutri-001',
        operatorName: 'Dr. Nutrizionista',
        date: '2024-10-01',
        startTime: '10:00',
        endTime: '11:00',
        duration: 60,
        type: 'evaluation',
        title: 'Prima visita nutrizionale',
        clinicalNotes: 'Peso 85 kg, altezza 174 cm, BMI 28. Obiettivo: 75 kg.',
        treatmentDescription:
          'Anamnesi alimentare, plicometria, impostazione piano alimentare personalizzato.',
        createdAt: '2024-10-01T11:00:00',
      },
      {
        id: 'treat-302',
        pathId: 'path-004',
        operatorId: 'op-nutri-001',
        operatorName: 'Dr. Nutrizionista',
        date: '2024-12-01',
        startTime: '10:00',
        endTime: '10:30',
        duration: 30,
        type: 'followup',
        title: 'Controllo mensile',
        clinicalNotes: 'Peso 82 kg. Perdita di 3 kg in 2 mesi. Buona compliance.',
        treatmentDescription: 'Verifica aderenza dieta, aggiustamenti piano alimentare.',
        createdAt: '2024-12-01T10:30:00',
      },
    ],
    documents: [
      {
        id: 'doc-301',
        pathId: 'path-004',
        name: 'Piano alimentare Ottobre',
        type: 'pdf',
        url: '/assets/mock-docs/piano-alimentare.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 234567,
        uploadedAt: '2024-10-01T12:00:00',
        category: 'piani',
      },
    ],
    createdAt: '2024-10-01T09:00:00',
    updatedAt: '2024-12-01T10:30:00',
  },

  // Percorso sospeso
  {
    id: 'path-005',
    patientId: '3',
    name: 'Riabilitazione spalla SX',
    description: 'Riabilitazione post-lussazione',
    diagnosis: 'Esiti lussazione spalla sinistra',
    primaryOperatorId: '',
    primaryOperatorName: 'Dr. Fisioterapista',
    status: 'suspended',
    startDate: '2024-09-15',
    plannedSessions: 15,
    completedSessions: 6,
    anamnesis: {
      id: 'anam-005',
      pathId: 'path-005',
      chiefComplaint: 'Limitazione funzionale spalla sinistra',
      historyOfPresentIllness:
        'Lussazione spalla SX avvenuta durante partita di basket. Riduzione in PS.',
      painScale: 4,
      painLocation: 'Spalla sinistra',
      patientGoals: 'Tornare a giocare a basket',
      therapistGoals: 'Recupero ROM, stabilizzazione, ritorno allo sport',
      createdAt: '2024-09-15T09:00:00',
      updatedAt: '2024-09-15T09:00:00',
      createdBy: 'op-fisio-001',
    },
    treatments: [],
    documents: [],
    notes: 'Percorso sospeso per impegni lavorativi del paziente. Da riprendere a gennaio.',
    internalNotes: 'Contattare paziente a inizio gennaio per ripresa.',
    createdAt: '2024-09-15T08:00:00',
    updatedAt: '2024-11-01T09:00:00',
  },
];

/**
 * Helper per ottenere mock paths filtrati per paziente
 */
export function getMockPathsByPatientId(patientId: string): TherapeuticPath[] {
  return MOCK_THERAPEUTIC_PATHS.filter((p) => p.patientId === patientId);
}

/**
 * Helper per ottenere un singolo mock path
 */
export function getMockPathById(pathId: string): TherapeuticPath | undefined {
  return MOCK_THERAPEUTIC_PATHS.find((p) => p.id === pathId);
}
