import { MigrationInterface, QueryRunner } from "typeorm";

export class Aggiuntacolonnepazienti1765320688586 implements MigrationInterface {
    name = 'Aggiuntacolonnepazienti1765320688586'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."persone_riferimento_genere_enum" AS ENUM('M', 'F', 'A', 'N')`);
        await queryRunner.query(`CREATE TYPE "public"."persone_riferimento_stato_civile_enum" AS ENUM('celibe_nubile', 'coniugato', 'separato', 'divorziato', 'vedovo', 'unione_civile')`);
        await queryRunner.query(`CREATE TYPE "public"."persone_riferimento_tipo_riferimento_enum" AS ENUM('genitore', 'tutore_legale', 'accompagnatore', 'coniuge', 'figlio_maggiorenne', 'altro_familiare', 'assistente_sociale', 'badante')`);
        await queryRunner.query(`CREATE TYPE "public"."persone_riferimento_tipo_patria_podesta_enum" AS ENUM('entrambi_genitori', 'genitore_singolo', 'genitori_separati', 'solo_padre', 'solo_madre', 'tutore_nominato', 'affidamento_congiunto')`);
        await queryRunner.query(`CREATE TYPE "public"."persone_riferimento_stato_relazione_enum" AS ENUM('attiva', 'sospesa', 'scaduta', 'revocata')`);
        await queryRunner.query(`CREATE TABLE "persone_riferimento" ("id" SERIAL NOT NULL, "nome" character varying(50) NOT NULL, "cognome" character varying(50) NOT NULL, "codice_fiscale" character varying(16), "data_nascita" date, "comune_nascita" character varying(100), "nazione_nascita" character varying(50) DEFAULT 'Italia', "luogo_nascita_estero" character varying(100), "genere" "public"."persone_riferimento_genere_enum" NOT NULL DEFAULT 'N', "stato_civile" "public"."persone_riferimento_stato_civile_enum", "indirizzo" character varying(100), "cap" character varying(20), "citta" character varying(50), "provincia" character varying(5), "nazioneResidenza" character varying(100), "telefono" character varying(20), "cellulare" character varying(20), "fax" character varying(20), "email" character varying(100), "pec" character varying(100), "tipo_riferimento" "public"."persone_riferimento_tipo_riferimento_enum" NOT NULL, "tipo_patria_podesta" "public"."persone_riferimento_tipo_patria_podesta_enum", "stato_relazione" "public"."persone_riferimento_stato_relazione_enum" NOT NULL DEFAULT 'attiva', "data_inizio" date NOT NULL, "data_fine" date, "motivo_fine" character varying(255), "puo_dare_consenso" boolean NOT NULL DEFAULT false, "puo_accedere_cartella" boolean NOT NULL DEFAULT false, "puo_ritirare_referti" boolean NOT NULL DEFAULT false, "puo_prenotare_visite" boolean NOT NULL DEFAULT false, "puo_ricevere_fatture" boolean NOT NULL DEFAULT false, "puo_essere_contattato" boolean NOT NULL DEFAULT true, "documento_nomina" character varying(255), "numero_pratica_tribunale" character varying(50), "tribunale_competente" character varying(100), "data_nomina_legale" date, "note" text, "note_legali" text, "istruzioni_speciali" text, "paziente_id" integer NOT NULL, "coniuge_paziente_id" integer, "attivo" boolean NOT NULL DEFAULT true, "creato_da_utente_id" integer, "modificato_da_utente_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cbc57a4a02a66e248b6f88b69ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_52f44319a09c2f43f4f263d0f1" ON "persone_riferimento" ("data_inizio", "data_fine") `);
        await queryRunner.query(`CREATE INDEX "IDX_030f2a02c84e609e3bbe492645" ON "persone_riferimento" ("paziente_id", "tipo_riferimento") `);
        await queryRunner.query(`CREATE INDEX "IDX_77884031fd62d48f830955f223" ON "persone_riferimento" ("email") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bdd975d6d67e535b64be94d79f" ON "persone_riferimento" ("codice_fiscale") WHERE codice_fiscale IS NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."paziente_persona_relazioni_tipo_trattamento_enum" AS ENUM('visita_generale', 'esame_diagnostico', 'trattamento_invasivo', 'chirurgia_minore', 'chirurgia_maggiore', 'trattamento_psicologico', 'anestesia', 'sperimentazione', 'emergenza')`);
        await queryRunner.query(`CREATE TYPE "public"."paziente_persona_relazioni_tipo_consenso_richiesto_enum" AS ENUM('singolo_genitore', 'entrambi_genitori', 'solo_tutore', 'qualsiasi_autorizzato')`);
        await queryRunner.query(`CREATE TYPE "public"."paziente_persona_relazioni_stato_consenso_enum" AS ENUM('non_richiesto', 'richiesto', 'parziale', 'completo', 'negato', 'scaduto')`);
        await queryRunner.query(`CREATE TABLE "paziente_persona_relazioni" ("id" SERIAL NOT NULL, "paziente_id" integer NOT NULL, "persona_riferimento_id" integer NOT NULL, "tipo_trattamento" "public"."paziente_persona_relazioni_tipo_trattamento_enum", "tipo_consenso_richiesto" "public"."paziente_persona_relazioni_tipo_consenso_richiesto_enum" NOT NULL DEFAULT 'singolo_genitore', "stato_consenso" "public"."paziente_persona_relazioni_stato_consenso_enum" NOT NULL DEFAULT 'non_richiesto', "consenso_dato" boolean NOT NULL DEFAULT false, "data_consenso" TIMESTAMP, "data_scadenza_consenso" TIMESTAMP, "modalita_consenso" character varying(50), "documento_consenso" character varying(255), "firma_digitale" text, "eta_minima_consenso_autonomo" integer, "richiede_consenso_fino_eta" integer, "allow_consenso_minore" boolean NOT NULL DEFAULT false, "note" text, "motivo_negazione" text, "motivo_revoca" text, "creato_da_utente_id" integer, "consenso_raccolto_da_utente_id" integer, "attivo" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3ebe5d6c34d06ca6f42b03b06b8" UNIQUE ("paziente_id", "persona_riferimento_id", "tipo_trattamento"), CONSTRAINT "PK_a2d49ea3c43a5a8bf906b76285d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6bfe4218cea4f10c8e9d92df44" ON "paziente_persona_relazioni" ("data_consenso") `);
        await queryRunner.query(`CREATE INDEX "IDX_74a7fd813968dcc416436ffaa3" ON "paziente_persona_relazioni" ("tipo_trattamento", "stato_consenso") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1fdda4f6872be98035e0534898" ON "paziente_persona_relazioni" ("paziente_id", "persona_riferimento_id") `);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "surname"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "nome" character varying(50) NOT NULL DEFAULT 'Nome'`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "cognome" character varying(50) NOT NULL DEFAULT 'Cognome'`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "codice_fiscale" character varying(16)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "data_nascita" date`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "comune_nascita" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "nazione_nascita" character varying(50) DEFAULT 'Italia'`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "luogo_nascita_estero" character varying(100)`);
        await queryRunner.query(`CREATE TYPE "public"."patients_genere_enum" AS ENUM('M', 'F', 'A', 'N')`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "genere" "public"."patients_genere_enum" NOT NULL DEFAULT 'N'`);
        await queryRunner.query(`CREATE TYPE "public"."patients_stato_civile_enum" AS ENUM('celibe_nubile', 'coniugato', 'separato', 'divorziato', 'vedovo', 'unione_civile')`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "stato_civile" "public"."patients_stato_civile_enum"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "indirizzo" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "cap" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "citta" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "provincia" character varying(5)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "telefono" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "fax" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "cellulare" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "pec" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "codiceSdi" character varying(10)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "nazioneResidenza" character varying(100)`);
        await queryRunner.query(`CREATE TYPE "public"."patients_tipo_paziente_enum" AS ENUM('adulto_autonomo', 'minorenne', 'disabile_con_tutore', 'anziano_con_tutore')`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "tipo_paziente" "public"."patients_tipo_paziente_enum" NOT NULL DEFAULT 'adulto_autonomo'`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "medico_base" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "gruppo_sanguigno" character varying(5)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "allergie" text`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "farmaci_uso" text`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "patologie_croniche" text`);
        await queryRunner.query(`CREATE TYPE "public"."patients_stato_anagrafica_enum" AS ENUM('bozza', 'parziale', 'completa', 'da_verificare')`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "stato_anagrafica" "public"."patients_stato_anagrafica_enum" NOT NULL DEFAULT 'bozza'`);
        await queryRunner.query(`CREATE TYPE "public"."patients_stato_privacy_enum" AS ENUM('non_acquisita', 'cartacea', 'digitale', 'mista')`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "stato_privacy" "public"."patients_stato_privacy_enum" NOT NULL DEFAULT 'non_acquisita'`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "consenso_privacy" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "data_consenso_privacy" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "consenso_marketing" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "consenso_ricerca_medica" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "modalita_consenso_per_trattamento" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "consenso_comunicazione_terzi" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "codice_paziente" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "UQ_35c47d8eb142907d4f887c5ef80" UNIQUE ("codice_paziente")`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "attivo" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "note_amministrative" text`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "convenzione_id" integer`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "data_ultima_modifica_privacy" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "richiesta_cancellazione" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "data_richiesta_cancellazione" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "data_anonimizzazione" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "conservazione_fino" date`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "name" character varying NOT NULL DEFAULT 'Nome'`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "surname" character varying NOT NULL DEFAULT 'Cognome'`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "phone" character varying NOT NULL DEFAULT '0000000000'`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "email" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "email" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_5ae1c5678291259a8fa83184e9" ON "patients" ("data_nascita") `);
        await queryRunner.query(`CREATE INDEX "IDX_46359b42cd949db0902fec024b" ON "patients" ("telefono") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4014d08fcce4b66b9c587a57a1" ON "patients" ("email") WHERE email IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9dd31ef1df1ae197ee914782af" ON "patients" ("codice_fiscale") `);
        await queryRunner.query(`ALTER TABLE "persone_riferimento" ADD CONSTRAINT "FK_99eebade3fbebaac4aa182d268f" FOREIGN KEY ("paziente_id") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "persone_riferimento" ADD CONSTRAINT "FK_15d51f7ad54a305d9c3210e6ca0" FOREIGN KEY ("coniuge_paziente_id") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paziente_persona_relazioni" ADD CONSTRAINT "FK_c3abc6d16bf05727201ba72ac29" FOREIGN KEY ("paziente_id") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paziente_persona_relazioni" ADD CONSTRAINT "FK_30c7a6964747d7929e44970036f" FOREIGN KEY ("persona_riferimento_id") REFERENCES "persone_riferimento"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "paziente_persona_relazioni" DROP CONSTRAINT "FK_30c7a6964747d7929e44970036f"`);
        await queryRunner.query(`ALTER TABLE "paziente_persona_relazioni" DROP CONSTRAINT "FK_c3abc6d16bf05727201ba72ac29"`);
        await queryRunner.query(`ALTER TABLE "persone_riferimento" DROP CONSTRAINT "FK_15d51f7ad54a305d9c3210e6ca0"`);
        await queryRunner.query(`ALTER TABLE "persone_riferimento" DROP CONSTRAINT "FK_99eebade3fbebaac4aa182d268f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9dd31ef1df1ae197ee914782af"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4014d08fcce4b66b9c587a57a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46359b42cd949db0902fec024b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ae1c5678291259a8fa83184e9"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "email" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "surname"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "conservazione_fino"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "data_anonimizzazione"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "data_richiesta_cancellazione"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "richiesta_cancellazione"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "data_ultima_modifica_privacy"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "convenzione_id"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "note_amministrative"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "attivo"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "UQ_35c47d8eb142907d4f887c5ef80"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "codice_paziente"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "consenso_comunicazione_terzi"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "modalita_consenso_per_trattamento"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "consenso_ricerca_medica"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "consenso_marketing"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "data_consenso_privacy"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "consenso_privacy"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "stato_privacy"`);
        await queryRunner.query(`DROP TYPE "public"."patients_stato_privacy_enum"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "stato_anagrafica"`);
        await queryRunner.query(`DROP TYPE "public"."patients_stato_anagrafica_enum"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "patologie_croniche"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "farmaci_uso"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "allergie"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "gruppo_sanguigno"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "medico_base"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "tipo_paziente"`);
        await queryRunner.query(`DROP TYPE "public"."patients_tipo_paziente_enum"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "nazioneResidenza"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "codiceSdi"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "pec"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "cellulare"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "fax"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "telefono"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "provincia"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "citta"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "cap"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "indirizzo"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "stato_civile"`);
        await queryRunner.query(`DROP TYPE "public"."patients_stato_civile_enum"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "genere"`);
        await queryRunner.query(`DROP TYPE "public"."patients_genere_enum"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "luogo_nascita_estero"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "nazione_nascita"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "comune_nascita"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "data_nascita"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "codice_fiscale"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "cognome"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "nome"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "surname" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fdda4f6872be98035e0534898"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74a7fd813968dcc416436ffaa3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bfe4218cea4f10c8e9d92df44"`);
        await queryRunner.query(`DROP TABLE "paziente_persona_relazioni"`);
        await queryRunner.query(`DROP TYPE "public"."paziente_persona_relazioni_stato_consenso_enum"`);
        await queryRunner.query(`DROP TYPE "public"."paziente_persona_relazioni_tipo_consenso_richiesto_enum"`);
        await queryRunner.query(`DROP TYPE "public"."paziente_persona_relazioni_tipo_trattamento_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdd975d6d67e535b64be94d79f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77884031fd62d48f830955f223"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_030f2a02c84e609e3bbe492645"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52f44319a09c2f43f4f263d0f1"`);
        await queryRunner.query(`DROP TABLE "persone_riferimento"`);
        await queryRunner.query(`DROP TYPE "public"."persone_riferimento_stato_relazione_enum"`);
        await queryRunner.query(`DROP TYPE "public"."persone_riferimento_tipo_patria_podesta_enum"`);
        await queryRunner.query(`DROP TYPE "public"."persone_riferimento_tipo_riferimento_enum"`);
        await queryRunner.query(`DROP TYPE "public"."persone_riferimento_stato_civile_enum"`);
        await queryRunner.query(`DROP TYPE "public"."persone_riferimento_genere_enum"`);
    }

}
